// Code generated by MockGen. DO NOT EDIT.
// Source: ./portal_app_store/data_source.go
//
// Generated by this command:
//
//	mockgen -source=./portal_app_store/data_source.go -destination=./portal_app_store/data_source_mock_test.go -package=portalappstore
//

// Package portalappstore is a generated GoMock package.
package store

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDataSource is a mock of DataSource interface.
type MockDataSource struct {
	ctrl     *gomock.Controller
	recorder *MockDataSourceMockRecorder
	isgomock struct{}
}

// MockDataSourceMockRecorder is the mock recorder for MockDataSource.
type MockDataSourceMockRecorder struct {
	mock *MockDataSource
}

// NewMockDataSource creates a new mock instance.
func NewMockDataSource(ctrl *gomock.Controller) *MockDataSource {
	mock := &MockDataSource{ctrl: ctrl}
	mock.recorder = &MockDataSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataSource) EXPECT() *MockDataSourceMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockDataSource) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockDataSourceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDataSource)(nil).Close))
}

// FetchInitialData mocks base method.
func (m *MockDataSource) FetchInitialData() (map[PortalAppID]*PortalApp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchInitialData")
	ret0, _ := ret[0].(map[PortalAppID]*PortalApp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchInitialData indicates an expected call of FetchInitialData.
func (mr *MockDataSourceMockRecorder) FetchInitialData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchInitialData", reflect.TypeOf((*MockDataSource)(nil).FetchInitialData))
}

// GetUpdateChannel mocks base method.
func (m *MockDataSource) GetUpdateChannel() <-chan PortalAppUpdate {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUpdateChannel")
	ret0, _ := ret[0].(<-chan PortalAppUpdate)
	return ret0
}

// GetUpdateChannel indicates an expected call of GetUpdateChannel.
func (mr *MockDataSourceMockRecorder) GetUpdateChannel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpdateChannel", reflect.TypeOf((*MockDataSource)(nil).GetUpdateChannel))
}
