global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # PEAS metrics (running locally on host)
  - job_name: 'peas'
    static_configs:
      - targets: ['host.docker.internal:9090']
    scrape_interval: 5s
    metrics_path: /metrics
    scheme: http
