name: Tag and release new version and push to GHCR

on:
  workflow_run:
    workflows: ["External Auth Server lint and test"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch: # Added to enable manual trigger via GitHub UI

jobs:
  tag-and-release:
    name: "Tag and release new version"
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ github.token }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      version: ${{ steps.release.outputs.version }}
    steps:
      - id: release
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: patch
          release_body: ":rocket: Release Notes !:fireworks: "
          use_github_release_notes: true

  build-and-push:
    name: "Build and push Docker image to GHCR"
    runs-on: "ubuntu-22.04"
    needs: [tag-and-release]
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history including tags

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/buildwithgrove/path-external-auth-server
          tags: |
            type=semver,pattern={{version}},value=${{ needs.tag-and-release.outputs.version }}
            type=sha

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64,linux/arm64
          file: Dockerfile
          context: .
